[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simplecsvcli"
version = "0.1.0"
description = "A small CLI for simple CSV inspection and transformation."
requires-python = ">=3.8"
authors = [ { name = "Sean O'Gary" } ]

[tool.setuptools.packages.find]
where = ["."]
include = ["cli*"]
